global:
  scrape_interval: 5s 
  evaluation_interval: 5s

scrape_configs:
  # 1. Scraping das métricas geradas pelo próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Scraping das métricas exportadas pelo OTel Collector (app -> collector -> port 8889)
  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8889']

  # 3. Scraping de métricas internas de performance do próprio OTel Collector
  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
